"""add retry_count to generation_job

Revision ID: 935297907504
Revises: 010_drop_llm_queue
Create Date: 2026-06-14 20:05:36.250317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935297907504'
down_revision = '010_drop_llm_queue'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_job', schema=None) as batch_op:
        batch_op.drop_column('retry_count')

    # ### end Alembic commands ###
